SELECT_FILE_PLACEHOLDER = "Chọn file excel dữ liệu"
CHOOSE_FILE = "Chọn file excel"
CREATE_PDF = "Tạo PDF"
CREATE_SUCCESS = "Tạo thành công"
PDF_OUTPUT_MSG = "PDFs have been generated and saved to:\n{}"
PROCESS_FILE_SUCCESS = "Xử lý file thành công"
PROCESS_FILE_FAILED = "Xử lý file thất bại"
EMPTY_FILE_NAME = "Không có file"
